### ISSUE TITLE
Replace text with icons where possible

### ISSUE THREAD

**Issue by s8subram** [cse110-sp21-group32/cse110-sp21-group32#38]
**Is your feature request related to a problem? Please describe.**
The text buttons for edit, details, etc. are clunky and take up excess space and cognitive load.

**Describe the solution you'd like**
To remedy this, we can replace the text with easily readable icons wherever applicable.

**(optional) Add visual aid of solution**
We have a visual of the icons on the Miro board for reference.

**Describe alternatives you've considered**
I can't really see a more concise way to express information than icons.

**Additional context**
N/A

**Comment by rajdama** [comment]
I can do it

**Comment by richardy2971** [comment]
Completed
